# Generated by Django 3.2 on 2021-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('HOD', 'HOD'), ('admin', 'admin')], max_length=20)),
                ('registerNumber', models.CharField(max_length=25)),
            ],
        ),
    ]
