# Generated by Django 3.2 on 2021-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80)),
                ('exam', models.TextField()),
                ('subject', models.TextField()),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
